### ISSUE TITLE
HANA DB Exporter in Kubernetis cluster

### ISSUE THREAD

**Issue by Connz21** [SUSE/hanadb_exporter#93] opened 2021-06-25 10:01 UTC
hi,
we have no SUSE Linux system, we are using RedHat Linux. Therefore, we want to install SUSE in a Kubernetes cluster. You recommend to install the exporter on the same machine where the HANA DB is running, but this is not possible.
we tried to install the Exporter on RedHat, but we get some errors.
Is the installation od SUSE and Exporter in a Kubernetes cluster also a recommended way?
we want to monitor 3 SAP HANA DB`s.
How do I have to setup the config.json file?

best regards

Conny

**Comment by diegoakechi** [comment] 2021-06-25 10:48
Hi @Connz21, in general Prometheus exporters are recommend to run in the same  machine as the application to avoid latency and other network issues, plus eventually need for access to local binaries and etc.

That said, the HANA DB exporter uses a normal DB connection to execute SQL, so technically it can work remotely like on your setup. You just need to point the right connection information and it should work.

We didn't test specifically inside a container, but we did test remote DB connection.

I don't know your expectations regarding enterprise support, but I recommend to check with your provider if this is a supported scenario.

**Comment by Connz21** [comment] 2021-06-25 11:05
hi ,
thanks for the quick answer
can I insert connection values for 3 different HANA DB`s in one config.json?

best regards

Conny

**Comment by diegoakechi** [comment] 2021-06-25 11:12
You will need 3 container in your case, one for each DB.

By design the exporter handles a single DB per instance, connecting also to the tenants DBs of this given DB. Multiple DBs are covered by scaling up the amount of Systemd services (containers on your case)

**Comment by Connz21** [comment] 2021-06-25 11:44
ok, I will discuss this with our OS colleagues

**Comment by diegoakechi** [comment] 2021-06-25 11:54
@Connz21 Can I assume it is fine to close this issue, correct?

**Comment by Connz21** [comment] 2021-06-25 11:57
Hi,
I have closed the issue

regrads

Von: Diego Akechi ***@***.***>
Gesendet: Freitag, 25. Juni 2021 13:55
An: SUSE/hanadb_exporter ***@***.***>
Cc: Maas, Konrad ***@***.***>; Mention ***@***.***>
Betreff: Re: [SUSE/hanadb_exporter] HANA DB Exporter in Kubernetis cluster (#93)


CAUTION: This e-mail is from an external sender. Do not click links or open attachments unless you recognize the sender and know the content is safe. Never provide your password!

@Connz21<https://github.com/Connz21> Can I assume it is fine to close this issue, correct?

**Closed** 2021-06-25 11:56 UTC
